spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/register_courses?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 123
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

server:
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true


